### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by HelloThisIsFlo** [skinny85/goos-book-code#1]
Hey,

As the title suggests, this is not an issue 😊
I just wanted to thank you. Your project make reading the GOOS book and following along **infinitely** easier 😍
Here is my version if you're interested: https://github.com/FlorianKempenich/GOOS
But it probably won't be of much use to you now 😁

Anyway, Thanks again, great work 😃👍

**Comment by skinny85** [comment]
Hey @FlorianKempenich , this is probably the best GitHub issue I've ever received, thanks 🙂. It's my pleasure, I'm glad you found the repo useful!

Take care,
Adam
